CREATE DATABASE inventory;
USE inventory;

CREATE TABLE `salesman` (
  `SALESMAN_ID` int(5) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(30) NOT NULL,
  `CITY` VARCHAR(15) NOT NULL,
  `COMMISSION` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`SALESMAN_ID`),
  UNIQUE KEY `SALESMAN_ID_UNIQUE` (`salesman_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `customer` (
  `CUSTOMER_ID` int(5) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(30) NOT NULL,
  `CITY` VARCHAR(15) NOT NULL,
  `GRADE` int(3) NOT NULL,
  `SALESMAN_ID` int(5) NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`),
  UNIQUE KEY `CUSTOMER_ID_UNIQUE` (`customer_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `orders` (
  `ORD_NO` int(5) NOT NULL AUTO_INCREMENT,
  `PURCH_AMT` DECIMAL(8,2) NOT NULL,
  `ORD_DATE` DATE NOT NULL,
  `CUSTOMER_ID` int(5) NOT NULL,
  `SALESMAN_ID` int(5) NOT NULL,
  PRIMARY KEY (`ORD_NO`),
  INDEX `CUSTOMER_idx` (`CUSTOMER_ID` ASC) VISIBLE,
  INDEX `SALESMAN_idx` (`SALESMAN_ID` ASC) VISIBLE,
  CONSTRAINT `CUSTOMER`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `inventory`.`customer` (`CUSTOMER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SALESMAN`
    FOREIGN KEY (`SALESMAN_ID`)
    REFERENCES `inventory`.`salesman` (`SALESMAN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    UNIQUE KEY `ORD_NO_UNIQUE` (`ord_no`)
 ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1
 ;